module.exports = [
  { t: 54.8, text: 'Tera sharmaana meri jaana' },
  { t: 58.5, text: 'Kabhi rakh lun chhupa ke' },
  { t: 61.5, text: 'Teri yaadein sabhi khwaabon mein mere' },
  { t: 66.0, text: 'Hai tu hi basi, tu hi basi' },
  { t: 70.7, text: 'Tu hi basi' },
  { t: 72.5, text: 'Tera sharmaana meri jaana' },
  { t: 76.5, text: 'Kabhi rakh lun chhupa ke' },
  { t: 79.9, text: 'Teri yaadein sabhi khwaabon mein mere' },
  { t: 84.8, text: 'Hai tu hi basi, tu hi basi' },
  { t: 89.0, text: 'Tu hi basi' },
  { t: 91.0, text: 'Teri yaad jo rahe na' },
  { t: 92.5, text: 'Meri khwaabon mein basa hai tu hi tu' },
  { t: 94.3, text: 'Sawaalon mein main rakh lun chhupa ke' },
  { t: 96.0, text: 'Mujhe tu hi to bigaade' },
  { t: 97.5, text: 'Meri aankhon mein saja hai tu hi tu' },
  { t: 99.3, text: 'Peechhe dekho' },
  { t: 100.2, text: 'Teri yaad jo rahi na' },
  { t: 101.9, text: 'Meri khwaabon mein basa hai tu hi tu' },
  { t: 104.1, text: 'Sawaalon mein main rakh lun chhupa ke' },
  { t: 105.6, text: 'Mujhe tu hi to bigaade' },
  { t: 107.0, text: 'Meri aankhon mein saja hai tu hi tu' },
  { t: 109.6, text: 'Khwaabon mein tu hi tu' },
  { t: 113.0, text: 'Main tere bin adhoora hoon' },
  { t: 117.5, text: 'Sanwaare tu bigaade' },
  { t: 121.8, text: 'Tu hai humsafar' },
  { t: 125.0, text: 'Kya khuda hai tu' },
  { t: 127.0, text: 'Palkon pe main rakh dun' },
  { t: 129.5, text: 'Mera ye jahaan taaron se saja dun tujhko' },
  { t: 137.0, text: 'Aaina dikha dun tujhko' },
  { t: 140.0, text: 'Meri tu raza' },
  { t: 141.6, text: 'Meri tu raza, meri tu raza' },
  { t: 145.0, text: 'Peechhe dekho raah' },
  { t: 146.2, text: 'Teri yaad jo rahi na' },
  { t: 147.5, text: 'Meri khwaabon mein basa hai tu hi tu' },
  { t: 149.6, text: 'Sawaalon mein main rakh lun chhupa ke' },
  { t: 151.4, text: 'Mujhe tu hi to bigaade' },
  { t: 152.8, text: 'Meri aankhon mein saja hai tu hi tu' },
  { t: 154.1, text: 'Peechhe dekho raah' },
  { t: 155.3, text: 'Teri yaad jo rahi na' },
  { t: 156.5, text: 'Meri khwaabon mein basa hai tu hi tu' },
  { t: 158.6, text: 'Sawaalon mein main rakh lun chhupa ke' },
  { t: 160.4, text: 'Mujhe tu hi to bigaade' },
  { t: 162.0, text: 'Meri aankhon mein saja hai tu hi tu' },
  { t: 164.5, text: 'Tera sharmaana meri jaana' },
  { t: 168.5, text: 'Kabhi rakh lun chhupa ke' },
  { t: 171.5, text: 'Teri yaadein sabhi khwaabon mein mere' },
  { t: 175.5, text: 'Hai tu hi basi, tu hi basi' },
  { t: 180.5, text: 'Tu hi basi' },
  { t: 182.5, text: 'Tera sharmaana meri jaana' },
  { t: 186.5, text: 'Kabhi rakh lun chhupa ke' },
  { t: 189.5, text: 'Teri yaadein sabhi khwaabon mein mere' },
  { t: 193.5, text: 'Hai tu hi basi' },
  { t: 196.4, text: 'Tu hi basi, tu hi basi' },
  { t: 199.5, text: 'Donon jahaan teri mohabbat mein haar ke' },
  { t: 204.0, text: 'Wo jaa raha hai koi shab-e-gham guzaar ke' },
  { t: 209.2, text: 'Veeran hai maikada khum-o-saaghar udaas hain' },
  { t: 213.0, text: 'Tum kya gaye ke rooth gaye din bahaar ke' },
];
