module.exports = [
  { t: 0.3, text: 'Coke Studio Bharat Season 3, subscribe now' },
  { t: 40.5, text: 'Kaayar jo the wo shayar bane' },
  { t: 44.0, text: 'Ab kya kya karein' },
  { t: 47.4, text: 'Ishq mein na kehte the kuch jo lage ke khoj mein' },
  { t: 53.8, text: 'Kya lafzon se chale naye aashiq' },
  { t: 59.8, text: 'Ishq mein tere hai Faiz bane' },
  { t: 64.6, text: 'Arz kiya hai, humne bhi likha kuch tere baare mein' },
  { t: 70.0, text: 'Hai aise tu lage ki gulab hai' },
  { t: 73.5, text: 'Aur aise tu lage ki gulab hai' },
  { t: 78.0, text: 'Baaghon mein dil ke khil ke' },
  { t: 82.4, text: 'In fizaaon mein saaye ho gaye' },
  { t: 89.5, text: 'Aur waise hum to tere hi ghulam hain' },
  { t: 93.5, text: 'Aur waise hum to tere hi ghulam hain' },
  { t: 97.5, text: 'Baadshah dil ke' },
  { t: 101.0, text: 'Teri baazi mein jo tu chahe to' },
  { t: 108.4, text: 'Doobe dilon ki kya nau banun main' },
  { t: 112.5, text: 'Khud tair paaun na aankhon mein' },
  { t: 118.0, text: 'Shayar ki fitrat mein hi doobna' },
  { t: 122.5, text: 'Main kya hi ladun toofanon se' },
  { t: 127.8, text: 'Ishq mein tere hain Faiz bane' },
  { t: 132.6, text: 'Arz kiya hai, humne bhi likha kuch tere baare mein' },
  { t: 137.8, text: 'Haathon ko sambhale mere haathon mein' },
  { t: 142.0, text: 'Kaise haathon ko sambhale mere haathon mein' },
  { t: 147.5, text: 'Jab tak neend na aaye in lakeeron mein' },
  { t: 152.5, text: 'Baatein ho aaye' },
  { t: 167.8, text: 'Sa re pa re sa re ga pa sa' },
  { t: 174.7, text: 'Re re ni sa re re sa pa' },
  { t: 200.3, text: 'Sabne to sab keh diya hai' },
  { t: 205.2, text: 'Kya hi kahun' },
  { t: 207.8, text: 'Jo abhi bhi ankaha hai' },
  { t: 219.5, text: 'Na meri jaan meri' },
  { t: 224.4, text: 'Na maane na jaa' },
  { t: 228.1, text: 'Kar kuch naya main' },
  { t: 250.1, text: 'Aise aise aise kaise waise' },
  { t: 253.5, text: 'Jaise jaise main padhun mere dil mein jo' },
  { t: 256.8, text: 'Meri aankhein bhi padhein teri aankhon ko' },
  { t: 261.0, text: 'Kya yeh mehfil mein baithe ya uthe' },
  { t: 267.4, text: 'Daude chale to' },
  { t: 273.7, text: 'Teri aankhon mein taareefon ki nawaaz hai' },
  { t: 279.1, text: 'Teri mehfil tere jaane se veeran hai' },
  { t: 284.0, text: 'Main bas shayar banun, sirf tu sunne aaye to' },
  { t: 293.1, text: 'Shayad swar banaun, sirf tu sunne aaye to' },
];
