module.exports = [
  { t: 27.3, text: 'Tujhse shuru' },
  { t: 30.4, text: 'Tujh pe khatm' },
  { t: 33.5, text: 'Meri zindagi ki dastaan' },
  { t: 39.5, text: 'Ho rooth gayi tu mujhse' },
  { t: 45.5, text: 'Aa gayi hai doori darmiyaan' },
  { t: 51.0, text: 'Ho jo kuch mera hai tere liye hai' },
  { t: 57.5, text: 'Jaaun main tere bin kahaan' },
  { t: 63.0, text: 'Le chal mujhe tu aisi jagah pe' },
  { t: 68.5, text: 'Pyaar hi tera ho jahaan' },
  { t: 75.5, text: 'Tere pyaar mein, intezaar mein' },
  { t: 81.0, text: 'Khud ko fanaa main kar gayi' },
  { t: 86.5, text: 'Ho chahat meri tujhse hi thi' },
  { t: 93.5, text: 'Par ab wo baatein na rahi' },
  { t: 99.0, text: 'Ho jaa jaa ke aayi waapas yahin pe' },
  { t: 104.5, text: 'Reh na saki main bin tere' },
  { t: 111.0, text: 'Khushiyan bhi roothi' },
  { t: 114.5, text: 'Sapne bhi toote' },
  { t: 117.5, text: 'Saath raha na tera' },
  { t: 146.5, text: 'Mere dil se yeh poochhe koi' },
  { t: 150.6, text: 'Guzri hai kya' },
  { t: 153.5, text: 'Bujhte diye se koi poochhe zara' },
  { t: 158.5, text: 'Chahat ke dariya mein maujein hazaar' },
  { t: 165.0, text: 'Hum to usi mein doobe, nikle na paar' },
  { t: 172.0, text: 'Raste yahaan ruk gaye' },
  { t: 177.0, text: 'Hum bhi yahin tham gaye' },
  { t: 183.5, text: 'Kitne gaye mausam naye' },
  { t: 189.5, text: 'Chhupke kahin kho gaye' },
  { t: 194.5, text: 'Ho kaali kaali raat din se kahe' },
  { t: 201.5, text: 'Taare sabhi so gaye' },
  { t: 231.5, text: 'Din bhar teri sochon mein rehna mera' },
  { t: 236.5, text: 'Har pal meri aankhon mein chehra tera' },
  { t: 243.5, text: 'Sukh dukh ke lamhon mein tera sahara' },
  { t: 248.4, text: 'Maanga tha jab bhi tujhse saath mila' },
  { t: 256.0, text: 'Bhool na paaungi kabhi' },
  { t: 260.4, text: 'Reh gayi jo baatein ankahi' },
  { t: 267.5, text: 'Phir bhi hai tu hi, kehna yahi hai' },
  { t: 273.0, text: 'Mit ke bhi mit na saki' },
  { t: 279.5, text: 'Dil mein jali jo agan thi' },
  { t: 284.0, text: 'Mar ke bhi bujh na saki' },
];
