module.exports = [
  { t: 35.2, text: 'Kya yahi pyaar hai' },
  { t: 37.2, text: 'Ya hai yeh tera sitam' },
  { t: 40.0, text: 'Ke tujhe hum bhula na sake' },
  { t: 45.5, text: 'Dil mera laachaar hai' },
  { t: 48.0, text: 'Aur ab toh mere zakhm bhi' },
  { t: 50.4, text: 'Mujhe yun rula na sake' },
  { t: 55.8, text: 'Kyun hai dil yeh' },
  { t: 59.7, text: 'Hai lagta kabhi' },
  { t: 62.3, text: 'Ke ho ke yahan bhi tu nahi' },
  { t: 67.5, text: 'Yeh khamoshiyan' },
  { t: 70.3, text: 'Sataayein mujhe' },
  { t: 73.0, text: 'Toh sun le meri yeh sadaayein' },
  { t: 76.6, text: 'Ke yeh aankhein hain nam' },
  { t: 80.0, text: 'Main tanha' },
  { t: 83.5, text: 'Tu jaane na' },
  { t: 85.5, text: 'Tu jaane na' },
  { t: 88.9, text: 'Ke tera sanam' },
  { t: 91.7, text: 'Hai ruswa' },
  { t: 94.2, text: 'Tu jaane na' },
  { t: 97.1, text: 'O beparwah' },
  { t: 99.6, text: 'Sambhalo mujhe' },
  { t: 101.5, text: 'Yeh maikada bewafa hai bada' },
  { t: 104.6, text: 'Ladkhada jaaunga' },
  { t: 109.6, text: 'Bacha lo mujhe, be-aasra hoon' },
  { t: 114.2, text: 'Yahan main khada' },
  { t: 116.8, text: 'Main kahan jaaunga' },
  { t: 121.6, text: 'Dil se hi' },
  { t: 123.1, text: 'Andheron mein hi deta jaaunga' },
  { t: 128.9, text: 'Main zindagi' },
  { t: 131.5, text: 'Yeh sargoshiyan' },
  { t: 134.5, text: 'Rulaayein mujhe' },
  { t: 137.0, text: 'Aur madhoshiyon ki hawaon mein' },
  { t: 141.9, text: 'Yeh aankhein hain nam' },
  { t: 144.9, text: 'Main tanha' },
  { t: 147.5, text: 'Tu jaane na' },
  { t: 149.5, text: 'Tu jaane na' },
  { t: 151.5, text: 'Ke tera sanam' },
  { t: 155.0, text: 'Hai ruswa' },
  { t: 158.2, text: 'Tu jaane na' },
  { t: 161.1, text: 'O beparwah' },
  { t: 182.4, text: 'O beparwah' },
];
