module.exports = [
  { t: 25.7, text: 'Maahi ve' },
  { t: 27.7, text: 'Teri ada pe jab se nigaahein padi' },
  { t: 34.0, text: 'Hum apne nahi rahe' },
  { t: 38.5, text: 'Soch mein khoya rahoon' },
  { t: 41.5, text: 'Teri aadat hai mujhko lagi' },
  { t: 46.5, text: 'Tu itni haseen' },
  { t: 50.5, text: 'Dil mera na jaane kyun chahe phir tujhe' },
  { t: 56.5, text: 'Jaise barson se jude ho silsile' },
  { t: 63.0, text: 'Main tera ho jaunga' },
  { t: 67.0, text: 'Keh de bas mujhe' },
  { t: 69.5, text: 'Lagta tujhko bhi hai yeh' },
  { t: 73.0, text: 'Ya phir humein bhool hai' },
  { t: 90.1, text: 'Ab toh piya bin roye' },
  { t: 93.3, text: 'Aankhon teri mein khoye' },
  { t: 96.5, text: 'Rehte hain hardam mere nain' },
  { t: 102.0, text: 'Chehra tera o yaara' },
  { t: 105.0, text: 'Chaand se bhi hai pyaara' },
  { t: 108.5, text: 'Tu hi hai mere dil ka chain' },
  { t: 114.0, text: 'Raahon mein aaye na' },
  { t: 116.3, text: 'Man se tera tazkara jaaye na' },
  { t: 119.5, text: 'Tere siva koi bhi bhaaye na' },
  { t: 122.8, text: 'Laage nahi bin tere dil mera jaane jaan' },
  { t: 126.8, text: 'Meri yaadon mein tu, waadon mein tu' },
  { t: 130.0, text: 'Hai iraadon mein tu' },
  { t: 132.0, text: 'Saare ke saare zamaane ko yun maine bhulaya hai' },
  { t: 137.0, text: 'Toh meri sun le sada' },
  { t: 140.0, text: 'Yeh dil mera na jaane kyun chahe phir tujhe' },
  { t: 146.5, text: 'Jaise barson se jude ho silsile' },
  { t: 153.0, text: 'Main tera ho jaunga' },
  { t: 157.0, text: 'Keh de bas mujhe' },
  { t: 159.5, text: 'Lagta tujhko bhi hai yeh' },
  { t: 163.0, text: 'Ya phir humein bhool hai' },
  { t: 167.5, text: 'Tera deewana' },
  { t: 171.5, text: 'Khud se begaana' },
  { t: 175.0, text: 'Zaalim zamaana' },
  { t: 178.5, text: 'Haaye main tera' },
  { t: 181.0, text: 'Jahan hai jo tu yahan hai' },
  { t: 186.5, text: 'Yehi dua hai' },
  { t: 191.0, text: 'Dil mera na jaane kyun chahe phir tujhe' },
  { t: 197.5, text: 'Jaise barson se jude ho silsile' },
  { t: 204.0, text: 'Main tera ho jaunga' },
  { t: 208.0, text: 'Keh de bas mujhe' },
  { t: 210.4, text: 'Lagta tujhko bhi hai yeh' },
  { t: 214.0, text: 'Ya phir humein bhool hai' },
  { t: 218.0, text: 'Tera deewana' },
  { t: 222.0, text: 'Khud se begaana' },
  { t: 226.0, text: 'Zaalim zamaana' },
  { t: 229.5, text: 'Haaye main tera' },
  { t: 232.0, text: 'Jahan hai jo tu yahan hai' },
  { t: 237.5, text: 'Yehi dua hai' },
];
