module.exports = [
  { t: 21.6, text: 'Kabhi raaste mein chalte phirte tumse' },
  { t: 25.3, text: 'Mushkilon se ladte bhidte khud se' },
  { t: 28.6, text: 'Kya likhoon padhoon kyun boloon main tumse' },
  { t: 32.0, text: 'Arz kya karoon safhon ko bhar' },
  { t: 34.3, text: 'Kabhi sheeshe mein khud ko jo dekhoon' },
  { t: 37.5, text: 'Aankhon mein khud ki tumhein pa loon' },
  { t: 40.8, text: 'Saanson mein tumko' },
  { t: 43.6, text: 'Apni main yun sambhaloon' },
  { t: 46.5, text: 'Saath lena phir karna tum' },
  { t: 49.7, text: 'Karna bhala kal mein lena' },
  { t: 54.0, text: 'Milein hum tum' },
  { t: 58.7, text: 'Thaame haath chalein' },
  { t: 61.5, text: 'Beete pal ko peechhe chhodein' },
  { t: 64.5, text: 'Mud ke na dekhein hum tum' },
  { t: 84.2, text: 'Chalo door kahin' },
  { t: 87.4, text: 'Nahi kuch bhi yahan' },
  { t: 90.5, text: 'Jahan nahi koi' },
  { t: 93.5, text: 'Sukoon hai wahin' },
  { t: 96.9, text: 'Afsaanon mein bhi kahani aisi nahi' },
  { t: 101.5, text: 'Jab jab tum saans lo' },
  { t: 105.5, text: 'Jee loon main zindagi' },
  { t: 109.0, text: 'Duniya jahan ki baat tumse keh doon' },
  { t: 113.1, text: 'Dil ki baaton mein lafz kho jaayein' },
  { t: 118.4, text: 'Aankhon se main yeh keh doon' },
  { t: 121.5, text: 'Karna ghabra na jaana' },
  { t: 124.6, text: 'Chhodo duniya ko' },
  { t: 128.0, text: 'Tum ho jaayein' },
  { t: 133.6, text: 'Haazir hoon main' },
  { t: 135.8, text: 'Tumhara hi hoon main' },
  { t: 138.5, text: 'Bolo ek dooje ke' },
  { t: 141.8, text: 'Ho jaayein hum' },
];
