module.exports = [
  { t: 16.0, text: 'Faasle' },
  { t: 19.2, text: 'Jhoothe silsile' },
  { t: 23.0, text: 'Toote hue dil' },
  { t: 27.1, text: 'Jaaye kahan' },
  { t: 31.1, text: 'Mujhe jo khushi' },
  { t: 35.1, text: 'Meri na kabhi' },
  { t: 39.1, text: 'Jaaye tere sang' },
  { t: 43.3, text: 'Jaaye tu jahan' },
  { t: 46.5, text: 'Meri yeh dua hai' },
  { t: 51.0, text: 'Ki tera jeevan' },
  { t: 55.1, text: 'Yun chalta rahe barqaraar' },
  { t: 146.9, text: 'Kya ho gaya' },
  { t: 154.9, text: 'Tere waaste' },
  { t: 158.8, text: 'Sabhi raaste' },
  { t: 163.2, text: 'Chhod ke main aaya' },
  { t: 170.9, text: 'Tu toh na mila' },
  { t: 179.0, text: 'Lekin mera dil' },
  { t: 183.4, text: 'Jaane tu kahan' },
  { t: 221.0, text: 'Jaaunga kahan' },
  { t: 224.6, text: 'Main toh yahan' },
  { t: 228.8, text: 'Tere dil ki' },
  { t: 231.5, text: 'Aahaton mein hoon' },
  { t: 236.9, text: 'Sapnon mein' },
  { t: 240.9, text: 'Sochon mein hai tu' },
  { t: 244.9, text: 'Har lamhe mein' },
  { t: 253.1, text: 'Dhadke dil tere hi liye' },
  { t: 261.4, text: 'Hoga kisi ka naam' },
  { t: 277.6, text: 'Jaa rahe' },
  { t: 285.5, text: 'Jaa raha' },
  { t: 293.7, text: 'Jaa rahi' },
];
