module.exports = [
  { t: 14.6, text: 'Chal diye tum kahan' },
  { t: 18.2, text: 'Neer bharne ke' },
  { t: 20.9, text: 'Yahan reh gaye hain kyun nishaan' },
  { t: 28.2, text: 'Is dil bechain ke' },
  { t: 31.8, text: 'Aansu mere nain ke' },
  { t: 34.8, text: 'Reh gaye hain jaane jaan' },
  { t: 41.5, text: 'Mere dardon se tumko yeh baatein hain' },
  { t: 44.9, text: 'Ke adhoori tere bin raatein hain' },
  { t: 48.5, text: 'Kisse waale yeh dil se na jaate hain' },
  { t: 53.6, text: 'Phir hum kyun har baar aate hain' },
  { t: 58.9, text: 'Tujhko manate hain' },
  { t: 61.3, text: 'Tere gun gaate hain' },
  { t: 64.5, text: 'Har ghadi' },
  { t: 69.0, text: 'Har pal duaon mein tujhko hi maangte hain' },
  { t: 76.0, text: 'Phir bhi tu kyun aata hai nahi' },
  { t: 103.3, text: 'Mujh mein jo koi kami hai thodi' },
  { t: 110.2, text: 'Poori woh tumse hai hui' },
  { t: 117.0, text: 'Jab tum yun aana' },
  { t: 120.5, text: 'Gale lag jaana' },
  { t: 123.9, text: 'Tere siva na hai koi' },
  { t: 129.4, text: 'Hum toh tumko pukaarte hain' },
  { t: 133.3, text: 'Yun yaad karte hain' },
  { t: 137.5, text: 'Dil jo ghabra jaata hai kabhi' },
  { t: 144.4, text: 'Khud ko sawaalon mein barbaad karte hain' },
  { t: 151.0, text: 'Jab tu jawaab deta hai nahi' },
  { t: 158.1, text: 'Chhodo yeh baat purani hai' },
  { t: 160.9, text: 'Phir se likhni yeh kahani hai' },
  { t: 164.5, text: 'Karte hain tumse yeh waada' },
  { t: 170.6, text: 'Toh hum har baar aayenge' },
  { t: 175.4, text: 'Tujhko manayenge' },
  { t: 178.7, text: 'Tere gun gaayenge' },
  { t: 182.5, text: 'Har ghadi' },
  { t: 185.5, text: 'Har pal duaon mein tujhko hi maangenge' },
  { t: 192.4, text: 'Tu aa hi jaayega' },
  { t: 196.3, text: 'Hai yakeen' },
  { t: 198.5, text: 'Ki main ankhiyan teri meri saanjha ve' },
  { t: 204.7, text: 'O maahi main hoya tera' },
  { t: 206.8, text: 'Das ki main karaan haaye' },
  { t: 210.4, text: 'O maahi tenu ki main ankhiyan' },
  { t: 213.5, text: 'Teri meri saanjha ve' },
  { t: 216.8, text: 'O maahi main hoya tera' },
  { t: 220.5, text: 'Das ki main karaan haaye shaava' },
  { t: 225.3, text: 'O maahi ki main ankhiyan' },
  { t: 228.3, text: 'Teri meri saanjha ve' },
  { t: 232.2, text: 'O maahi hoya tera' },
  { t: 234.4, text: 'Das ki main karaan shaava' },
  { t: 239.0, text: 'O maahi' },
];
