module.exports = [
  { t: 12.7, text: 'Maine dekha tha usko' },
  { t: 18.0, text: 'Jahan baitha tha kal ko' },
  { t: 23.3, text: 'Hoor jaisi woh dikhti kyun' },
  { t: 29.7, text: 'Nazrein na hatti' },
  { t: 33.0, text: 'Humne bhi kuch na kaha' },
  { t: 38.0, text: 'Usne bhi kuch na kaha' },
  { t: 43.5, text: 'Baatein dilon ki jo reh gayi' },
  { t: 49.0, text: 'Yeh hai kahani us roz ki' },
  { t: 53.5, text: 'Yeh jo kahani hai jo hamari' },
  { t: 59.0, text: 'Hogi kabhi na poori' },
  { t: 65.5, text: 'Baat hamari jo na kahi thi' },
  { t: 69.5, text: 'Reh gayi hai woh adhoori' },
  { t: 97.6, text: 'Mehsoos mujhko jo tha hua' },
  { t: 102.5, text: 'Kaise karoon lafzon se bayaan' },
  { t: 108.0, text: 'Dil mein jo tha woh na keh saka' },
  { t: 113.5, text: 'Milke bhi tujhse na mil saka' },
  { t: 121.5, text: 'Aisi kya wajah' },
  { t: 125.9, text: 'Mere jo saamne thi' },
  { t: 130.5, text: 'Phir bhi meri kyun na tum ho saki' },
  { t: 140.0, text: 'Kismat meri khel rahi thi' },
  { t: 146.6, text: 'Majboori se' },
  { t: 150.8, text: 'Nazrein hamari jo na mili thi' },
  { t: 156.0, text: 'Yehi taqdeer thi meri' },
  { t: 161.6, text: 'Baatein hamari jo na kahi thi' },
  { t: 167.5, text: 'Reh gayi hai woh adhoori' },
  { t: 172.5, text: 'Yeh jo kahani hai jo hamari' },
  { t: 178.5, text: 'Hogi kabhi na poori' },
];
