module.exports = [
  { t: 13.4, text: 'Karti ja karti ja' },
  { t: 15.7, text: 'Mere dil ko tu chaknachoor karti ja' },
  { t: 21.0, text: 'Karti ja zaahir' },
  { t: 24.9, text: 'Jo tera yeh guroor' },
  { t: 28.6, text: 'Mujhe tu yeh batati ja' },
  { t: 31.0, text: 'Is zakhm ka marham kya' },
  { t: 35.4, text: 'Kyun thodi rasm-e-wafa' },
  { t: 38.6, text: 'Imtihaan badhana' },
  { t: 43.5, text: 'Kaise yeh hua khasara' },
  { t: 47.1, text: 'Na mein sambhla dobara' },
  { t: 50.6, text: 'Haaye na qaraar dil ko tere bin saiyaan' },
  { t: 57.6, text: 'Maine toh nibhaya' },
  { t: 61.4, text: 'Saath bada' },
  { t: 65.2, text: 'Tune toh khaak dhoondi manzil' },
  { t: 71.5, text: 'Tu rooth ja' },
  { t: 74.4, text: 'Kabool na humein' },
  { t: 78.6, text: 'Tu door ja toh khaak hum jiye' },
  { t: 85.8, text: 'Qurbat jo thi' },
  { t: 89.0, text: 'Jhoot se bhari' },
  { t: 93.0, text: 'Rooh meri tumhe dekh toh jaati' },
  { t: 100.2, text: 'Log karte hain tumse doori' },
  { t: 107.7, text: 'Kahani teri meri hai adhoori' },
  { t: 114.6, text: 'Hai dua sada' },
  { t: 118.0, text: 'Tu raho jahan bhi jaana' },
  { t: 121.8, text: 'Tu jeeta mein haara' },
  { t: 124.8, text: 'Reh hi gaya kehne ko kya' },
  { t: 128.5, text: 'Humne toh tha nibhaya' },
  { t: 132.6, text: 'Saath bada' },
  { t: 135.9, text: 'Tune toh khaak dhoondi manzil' },
  { t: 143.8, text: 'Kaise yeh hua khasara' },
  { t: 146.6, text: 'Na mein sambhla dobara' },
  { t: 150.2, text: 'Aaye na qaraar' },
  { t: 152.0, text: 'Dil ko hai bebasi yahan' },
];
