module.exports = [
  { t: 20.3, text: 'Kaagaz ke phool' },
  { t: 23.0, text: 'Laaun tere liye' },
  { t: 26.3, text: 'Khat likhoon' },
  { t: 29.6, text: 'Tere liye' },
  { t: 32.5, text: 'Main khuda ko maanu nahi' },
  { t: 37.1, text: 'Par maangu dua' },
  { t: 40.2, text: 'Tere liye' },
  { t: 44.2, text: 'Tere liye' },
  { t: 47.0, text: 'Ghar banaun' },
  { t: 49.7, text: 'Deewar neele rang se sajaun' },
  { t: 53.0, text: 'Pasand hai tumhein' },
  { t: 57.7, text: 'Maloom hai' },
  { t: 59.5, text: 'Tumne bataya tha ek dafa' },
  { t: 65.8, text: 'Neele phool laa raha hoon' },
  { t: 69.0, text: 'Tere liye' },
  { t: 72.2, text: 'Khat likhoon' },
  { t: 75.0, text: 'Tere liye' },
  { t: 78.6, text: 'Main khuda ko maanu nahi' },
  { t: 82.0, text: 'Par maangu dua' },
  { t: 85.6, text: 'Tere liye' },
  { t: 109.0, text: 'Teri baatein' },
  { t: 111.6, text: 'Nasamajh si' },
  { t: 114.2, text: 'Phir bhi jaayaz lag rahi hain' },
  { t: 119.5, text: 'Tu pareshan kar rahi hai' },
  { t: 125.0, text: 'Phir bhi maasoom lag rahi hai' },
  { t: 129.5, text: 'Tere liye' },
  { t: 132.3, text: 'Mandir jaaun' },
  { t: 135.5, text: 'Tere naam ka diya jalaun' },
  { t: 140.2, text: 'Hansta rahe tu chahe jo ho' },
  { t: 144.0, text: 'Teri hansi ko' },
  { t: 146.7, text: 'Kisi ki nazar na lage' },
  { t: 151.0, text: 'Kaagaz ke phool' },
  { t: 153.7, text: 'Laaun tere liye' },
  { t: 157.6, text: 'Khat likhoon' },
  { t: 160.3, text: 'Tere liye' },
  { t: 162.5, text: 'Main khuda ko maanu nahi' },
  { t: 168.5, text: 'Par maangu dua' },
  { t: 172.3, text: 'Tere liye' },
  { t: 215.0, text: 'Tere liye hum bane hain' },
  { t: 219.0, text: 'Tere liye' },
  { t: 222.6, text: 'Badal rahe hain kya' },
  { t: 226.0, text: 'Mohabbat ho gayi hai' },
  { t: 230.5, text: 'Mere hi teri baatein karein' },
  { t: 236.3, text: 'Tere liye' },
  { t: 239.0, text: 'Ghar banaun' },
  { t: 241.7, text: 'Deewar neele rang se sajaun' },
  { t: 245.0, text: 'Pasand hai tujhe' },
  { t: 248.2, text: 'Maloom hai' },
  { t: 250.9, text: 'Tune bataya tha ek dafa' },
  { t: 265.7, text: 'Dekh shayar ban gaya' },
  { t: 269.6, text: 'Tere liye naghma likha' },
  { t: 275.0, text: 'Tere liye' },
  { t: 278.0, text: 'Main khuda ko maanu kyun' },
  { t: 283.0, text: 'Tu khuda' },
  { t: 287.1, text: 'Tere liye' },
];
