module.exports = [
  { t: 9.7, text: 'Soniya re' },
  { t: 12.4, text: 'Soniya' },
  { t: 14.2, text: 'Soniya ve soniya' },
  { t: 16.5, text: 'Jad soniya tu lena mera naam' },
  { t: 20.0, text: 'Khalo ja osse thaan te' },
  { t: 23.0, text: 'Fad meri baanh soniya' },
  { t: 26.2, text: 'Le ja door main ishq \'ch choor' },
  { t: 29.5, text: 'Mere val haan tu mod ke aana' },
  { t: 33.5, text: 'Soniya jadon soniya tu lena mera naam' },
  { t: 38.5, text: 'Khalo ja osse thaan te' },
  { t: 41.0, text: 'Fad meri baanh soniya' },
  { t: 44.0, text: 'Le ja door main ishq \'ch choor' },
  { t: 48.6, text: 'Mere val haan tu mod ke aana' },
  { t: 52.7, text: 'Soniya' },
  { t: 54.6, text: 'Soniya ve' },
  { t: 57.2, text: 'Soniya soniya' },
  { t: 61.7, text: 'Soniya' },
  { t: 64.1, text: 'Soniya' },
  { t: 66.2, text: 'Soniya' },
  { t: 71.0, text: 'Soniya' },
  { t: 72.8, text: 'Paani dariyaavan da' },
  { t: 75.0, text: 'Rang hai hawaavan da' },
  { t: 76.4, text: 'Saath saade saahwan da' },
  { t: 79.9, text: 'Pyaar diyan chhaawan da' },
  { t: 82.5, text: 'Lambi lambi raahwan da' },
  { t: 85.4, text: 'Supna laavan da' },
  { t: 88.9, text: 'Paani dariyaavan da' },
  { t: 92.0, text: 'Rang hai hawaavan da' },
  { t: 94.8, text: 'Saath saade saahwan da' },
  { t: 97.8, text: 'Pyaar diyan chhaawan da' },
  { t: 100.5, text: 'Lambi lambi raahwan da' },
  { t: 103.3, text: 'Supna laavan da' },
  { t: 106.0, text: 'Jadon soniya tu lena mera naam' },
  { t: 109.5, text: 'Khalo ja osse thaan te' },
  { t: 112.5, text: 'Fad meri baanh soniya' },
  { t: 115.5, text: 'Le ja door main ishq \'ch choor' },
  { t: 119.0, text: 'Mere vallon haan tu mod ke aana' },
  { t: 123.0, text: 'Soniya jad soniya tu lena mera naam' },
  { t: 128.5, text: 'Khalo ja osse thaan te' },
  { t: 131.5, text: 'Fad meri baanh soniya' },
  { t: 134.5, text: 'Le ja door main ishq \'ch choor' },
  { t: 138.5, text: 'Mere val haan tu mod ke aana' },
  { t: 142.4, text: 'Soniya' },
  { t: 144.3, text: 'Soniya re' },
  { t: 147.0, text: 'Soniya soniya' },
  { t: 151.4, text: 'Soniya' },
  { t: 153.9, text: 'Soniya' },
  { t: 155.9, text: 'Soniya' },
  { t: 158.5, text: 'Soniya' },
  { t: 176.1, text: 'Soniya' },
  { t: 178.8, text: 'Soniya' },
];
