module.exports = [
  { t: 14.1, text: 'Mile to tu kabhi nahi' },
  { t: 20.5, text: 'Meri hasrat kyun bhadkaayi bewajah' },
  { t: 28.0, text: 'Ke tum bina jiye gaye' },
  { t: 32.5, text: 'Hua kaise na yeh jeena' },
  { t: 47.4, text: 'Dariya mere dil ka yeh behta na' },
  { t: 52.3, text: 'Dukhi dil ki sada kuch yeh kehta na' },
  { t: 56.0, text: 'Iski khamoshi ki tu wajah hai na' },
  { t: 59.0, text: 'Dil se tang aa gaya yehi saza hai na' },
  { t: 62.0, text: 'Ulfaton mein nahi koi paimana' },
  { t: 66.0, text: 'Mere apnon ka mujhse yeh kehna tha' },
  { t: 69.5, text: 'Surmayi teri aankhon mein beh jaana' },
  { t: 73.0, text: 'Kya pata tere gham mein hi rehna tha' },
  { t: 80.4, text: 'Rehna tha' },
  { t: 85.5, text: 'Kyun yun sehte sehte dil ko gham kha chuka meri jaan' },
  { t: 93.0, text: 'Kyun yun rehte rehte dikhe na koi disha' },
  { t: 99.5, text: 'Kyun yun sehte sehte dil ko gham kha chuka meri jaan' },
  { t: 107.0, text: 'Kyun yun rehte rehte dikhe na koi disha' },
  { t: 112.0, text: 'Jo tu nahi to aisa main chehra' },
  { t: 115.5, text: 'Ke jiski khoobsurti maand padi ho' },
  { t: 120.0, text: 'Aisa main dariya jo behna na chahe' },
  { t: 125.5, text: 'Jo tu nahi to aisa main chehra' },
  { t: 129.5, text: 'Ke jiski khoobsurti maand padi ho' },
  { t: 133.5, text: 'Aisa main dariya jo behna na chahe' },
  { t: 140.5, text: 'Dariya mere dil ka yeh behta na' },
  { t: 144.5, text: 'Dukhi dil ki sada kuch yeh kehta na' },
  { t: 147.5, text: 'Iski khamoshi ki tu wajah hai na' },
  { t: 150.5, text: 'Dil se tang aa gaya yehi saza hai na' },
  { t: 153.5, text: 'Ulfaton mein nahi koi paimana' },
  { t: 157.0, text: 'Mere apnon ka mujhse yeh kehna tha' },
  { t: 160.5, text: 'Surmayi teri aankhon mein beh jaana' },
  { t: 164.2, text: 'Kya pata tere gham mein hi rehna tha' },
  { t: 169.1, text: 'Kya pata tere gham mein hi rehna tha' },
  { t: 174.0, text: 'Aisa main dariya jo behna na chahe' },
];
