module.exports = [
  { t: 21.6, text: 'Kya bataun in sawaalon mein' },
  { t: 29.0, text: 'Kab se yun phasa hoon' },
  { t: 32.6, text: 'Raakh saare safhe par likh raha hoon' },
  { t: 37.4, text: 'Fasaane mein zindagi ke' },
  { t: 40.5, text: 'Mann ko kaise' },
  { t: 43.5, text: 'Aur kaise behlaun' },
  { t: 48.7, text: 'Tukde kaanch ke bikhre zameen par' },
  { t: 54.8, text: 'Chalna chahun par chhaya har kadam' },
  { t: 64.0, text: 'Dua saans lena' },
  { t: 83.2, text: 'Saza ye wafa' },
  { t: 87.1, text: 'To bazaar mein bike' },
  { t: 90.5, text: 'Ek chehra haqeeqat' },
  { t: 95.5, text: 'Dher saari kyun lage' },
  { t: 99.3, text: 'Hain khud ki khoj mein sab hi' },
  { t: 102.5, text: 'Haal dil mein ab kaise samjhaun' },
  { t: 108.5, text: 'Hai ye uljhe dhaagon sa' },
  { t: 114.0, text: 'Meri soch ka jahaan' },
  { t: 122.4, text: 'Tukde kaanch ke bikhre zameen par' },
  { t: 127.5, text: 'Chalna chahun par' },
  { t: 131.8, text: 'Chhaya har kadam' },
  { t: 137.8, text: 'Dua saans lena' },
  { t: 208.8, text: 'Andar tere raaz kai' },
  { t: 220.0, text: 'Hai andar tere raaz kai' },
  { t: 227.0, text: 'Khud se jo mil paayega wo' },
  { t: 232.3, text: 'Yaara dil se jo sun paayega' },
  { t: 238.0, text: 'Na chhod aas ki dor ko' },
  { t: 244.5, text: 'Sach tu samajh jaayega' },
  { t: 249.5, text: 'O yaara phir tu sambhal jaayega' },
];
