module.exports = [
  { t: 34.6, text: 'Haathon mein haath, aankhon mein aankhein' },
  { t: 40.0, text: 'Na chhoote yeh saath' },
  { t: 44.8, text: 'Aaye na kal, guzre na pal' },
  { t: 49.0, text: 'Aur kate na yeh raat' },
  { t: 53.5, text: 'Kuch na kaho, aao suno' },
  { t: 58.4, text: 'Seene mein dil yeh dhadakta hua' },
  { t: 65.0, text: 'Kuch na kaho, aao suno' },
  { t: 70.0, text: 'Wo tumse jo main nahi keh saka' },
  { t: 77.8, text: 'Pyaar mein rehna sada hai tere pyaar mein' },
  { t: 88.9, text: 'Haar mein jeete huye hain hum is haar mein' },
  { t: 98.0, text: 'Is haar mein' },
  { t: 101.0, text: 'Bas aise rahe' },
  { t: 104.5, text: 'Baahon mein meri tu aise rahe' },
  { t: 111.5, text: 'Bas aansu mere behte the jaise' },
  { t: 117.0, text: 'Tere na bahe' },
  { t: 120.5, text: 'Chhodo gila jo bhi hua' },
  { t: 126.0, text: 'Kaafi hai yeh tum mere paas' },
  { t: 131.0, text: 'Wo meri suna ke hai dua teri' },
  { t: 137.0, text: 'Tere liye mera ehsaas' },
  { t: 144.3, text: 'Ho pyaar mein rehna sada hai tere pyaar mein' },
  { t: 155.4, text: 'Ho haar mein jeete huye hain hum is haar mein' },
  { t: 164.5, text: 'Is haar mein' },
  { t: 168.5, text: 'Pyaar mein rehna sada hai tere pyaar mein' },
  { t: 177.6, text: 'Ho haar mein jeete huye hain hum is haar mein' },
  { t: 186.5, text: 'Is haar mein' },
  { t: 209.3, text: 'Is haar mein' },
];
