module.exports = [
  { t: 11.2, text: 'Loki kayi rus ke nahi mannde' },
  { t: 14.0, text: 'Ho gaye evein badnaam' },
  { t: 16.2, text: 'Peechhe mere hansde' },
  { t: 18.8, text: 'Phir puchhde mera haal' },
  { t: 21.4, text: 'Te mera koi jawaab' },
  { t: 24.0, text: 'Jidhar bhi jaawan' },
  { t: 26.6, text: 'Le sabr imtehaan' },
  { t: 29.6, text: 'Kiven main bataawan' },
  { t: 32.6, text: 'Eh duniya badi beimaan' },
  { t: 35.5, text: 'Loki kayi rus ke hain bhool gaye' },
  { t: 39.0, text: 'Rakhda na har koi maan' },
  { t: 42.7, text: 'Dil bada toota' },
  { t: 45.4, text: 'Par sukh bhi hai dekhe' },
  { t: 48.7, text: 'Chalta chalun par ye saza' },
  { t: 54.6, text: 'Kab tak yun doge' },
  { t: 57.5, text: 'Main saare ka saara' },
  { t: 60.6, text: 'Jal sa gaya, uthta dhuaan' },
  { t: 66.3, text: 'Sun balliye sun balliye' },
  { t: 69.5, text: 'Kamle dil de maare' },
  { t: 72.3, text: 'Ki kariye ki kariye' },
  { t: 75.3, text: 'Eh maamla vas ton baahre' },
  { t: 78.3, text: 'Sun balliye sun balliye' },
  { t: 82.3, text: 'Akhiyaan vich hanju hazaare' },
  { t: 84.4, text: 'Seene vich dil nahi hai' },
  { t: 87.5, text: 'Ishq da ban gaya mazaare' },
  { t: 101.4, text: 'Ajnabi jo hue kaise tum' },
  { t: 105.5, text: 'Chal diye kahaan gaye' },
  { t: 109.1, text: 'Laapata laapata' },
  { t: 113.4, text: 'Dil mein jo ranjishein' },
  { t: 116.5, text: 'Bhari hain arse se' },
  { t: 120.0, text: 'Kaise hum wo karein ab juda' },
  { t: 125.4, text: 'Gaya jaane kya zamaana' },
  { t: 129.4, text: 'Ye uljha fasaana' },
  { t: 132.7, text: 'Kehne ko keh dun par na aaye suljhaana' },
  { t: 137.9, text: 'Tumhein lagaana galti meri banaana' },
  { t: 140.3, text: 'Karun jurmaana' },
  { t: 142.2, text: 'Chalo maikhaana kholo tehkhaana' },
  { t: 144.8, text: 'Rakh di hai mehfil' },
  { t: 146.6, text: 'Tumse kya chhupaana kya chhupaana' },
  { t: 149.5, text: 'Nahi jaana' },
  { t: 150.7, text: 'Na meri koi khata thi na unki thi' },
  { t: 156.7, text: 'Waqt ke aage kisi ki nahi chalti' },
  { t: 162.7, text: 'Dil bada toota' },
  { t: 165.4, text: 'Par sukh bhi hai dekhe' },
  { t: 168.7, text: 'Chalta hoon main bas ek sila' },
  { t: 174.3, text: 'Sun balliye sun balliye' },
  { t: 176.6, text: 'Kamle dil de maare' },
  { t: 180.4, text: 'Ki kariye ki kariye' },
  { t: 183.5, text: 'Eh maamla vas ton baahre' },
  { t: 186.4, text: 'Jaanan wala jaane nahi' },
  { t: 189.5, text: 'Reh ke bhi o maan nahi de' },
  { t: 192.4, text: 'Saath bhi te saath nahi de' },
  { t: 195.5, text: 'Rakhe mera bhi maan' },
  { t: 199.0, text: 'Jaanan wala jaane nahi' },
  { t: 202.5, text: 'Reh ke bhi o maan nahi de' },
  { t: 204.9, text: 'Saath bhi te saath nahi de' },
  { t: 207.4, text: 'Kabhi kabhi' },
];
