module.exports = [
  { t: 22.2, text: 'O sanam o jigar' },
  { t: 25.2, text: 'Tum kaho kya hai khabar' },
  { t: 28.1, text: 'Kaise katein yeh raatein hain' },
  { t: 31.7, text: 'Kehte hain sab magar' },
  { t: 34.2, text: 'Koi chala na in par' },
  { t: 36.8, text: 'Raaste jo maine naape hain' },
  { t: 39.4, text: 'Kabhi hai taaron ki jhilmil' },
  { t: 42.0, text: 'Kabhi na dikhti manzil' },
  { t: 44.4, text: 'Aisa safar mera' },
  { t: 48.7, text: 'Main bhaaga bhaaga sadiyon se jaaga' },
  { t: 52.0, text: 'Aaya hoon meelon door se' },
  { t: 57.8, text: 'Na humsafar koi na apna ghar' },
  { t: 61.5, text: 'Yaara behta hoon nadiya pe' },
  { t: 76.7, text: 'Dikhte hain khwaab jo jaagti aankhon ko' },
  { t: 82.4, text: 'Sapne nahi iraade hain' },
  { t: 86.0, text: 'Poore woh karne ko' },
  { t: 88.8, text: 'Chal pade nange pairon' },
  { t: 91.6, text: 'Khud se kiye jo waade hain' },
  { t: 94.8, text: 'Rukna na kabhi bhi tha' },
  { t: 97.3, text: 'Chalna hi toh hai manzil' },
  { t: 100.0, text: 'Main na kahin thehra' },
  { t: 104.3, text: 'Main bhaaga bhaaga sadiyon se jaaga' },
  { t: 108.0, text: 'Aaya hoon meelon door se' },
  { t: 113.2, text: 'Na humsafar koi na apna ghar' },
  { t: 117.0, text: 'Yaara behta hoon nadiya pe' },
  { t: 122.7, text: 'Main bhaaga bhaaga sadiyon se jaaga' },
  { t: 126.5, text: 'Aaya ummeedon ka karke iraada' },
  { t: 131.0, text: 'Main bhaaga bhaaga sadiyon se jaaga' },
  { t: 137.0, text: 'Aaya hoon meelon door karke iraada' },
  { t: 142.4, text: 'Haath ki lakeeron mein' },
  { t: 144.6, text: 'Na khone diya khwaab ko taabeer mein' },
  { t: 146.6, text: 'Shehar ki hawa ne mujh mein rang bhare' },
  { t: 149.5, text: 'Main bhoola purani tasveeron mein' },
  { t: 152.2, text: 'Likha haath ki lakeeron mein' },
  { t: 154.0, text: 'Na khone diya khwaabon ko taabeer mein' },
  { t: 156.2, text: 'Dekh ke rab ne aazmaya mujhe' },
  { t: 159.2, text: 'Par diye sab kuch taqdeer se' },
  { t: 161.0, text: 'Likha haath ki lakeeron mein' },
  { t: 163.5, text: 'Na khone diya khwaab ko taabeer mein' },
  { t: 165.5, text: 'Shehar ki hawa ne mujh mein rang bhare' },
  { t: 168.5, text: 'Main bhoola purani tasveeron mein' },
  { t: 170.8, text: 'Likha haath ki lakeeron mein' },
  { t: 173.0, text: 'Na khone diya khwaab ko taabeer mein' },
  { t: 175.2, text: 'Dekh ke rab ne aazmaya mujhe' },
  { t: 177.8, text: 'Par diye sab kuch taqdeer se' },
  { t: 179.8, text: 'Likha haath ki lakeeron mein' },
  { t: 181.8, text: 'Na khone diya khwaab ko taabeer mein' },
  { t: 184.0, text: 'Shehar ki hawa ne mujh mein rang bhare' },
  { t: 186.8, text: 'Main bhoola purani tasveeron mein' },
  { t: 188.5, text: 'Likha haath ki lakeeron mein' },
  { t: 190.5, text: 'Na khone diya khwaab ko taabeer mein' },
  { t: 192.5, text: 'Dekh ke rab ne aazmaya mujhe' },
  { t: 195.0, text: 'Par diye sab kuch taqdeer se' },
  { t: 197.0, text: 'Likha haath ki lakeeron mein' },
  { t: 199.3, text: 'Na khone diya khwaab ko taabeer mein' },
  { t: 201.5, text: 'Shehar ki hawa ne mujh mein rang bhare' },
  { t: 204.5, text: 'Main bhoola purani tasveeron mein' },
  { t: 206.8, text: 'Likha haath ki lakeeron mein' },
  { t: 209.5, text: 'Na khone diya khwaab ko taabeer mein' },
  { t: 211.3, text: 'Dekh ke rab ne aazmaya mujhe' },
  { t: 213.1, text: 'Par diya sab kuch taqdeeron se' },
];
