module.exports = [
  { t: 0.9, text: 'Le chal mujhe yahan se' },
  { t: 9.2, text: 'Parey wahan par kahin' },
  { t: 13.5, text: 'Jidhar main hoon' },
  { t: 19.2, text: 'Bekhata tanhaiyon mein' },
  { t: 24.0, text: 'Kyun is bheed mein meri' },
  { t: 31.6, text: 'Sada kyun nahi tu sun raha' },
  { t: 39.0, text: 'Dhoondhun tujhe har jagah' },
  { t: 45.0, text: 'Tu na mile' },
  { t: 50.2, text: 'Gustakhiyan ke hain' },
  { t: 54.0, text: 'Ajab yeh silsile' },
  { t: 59.0, text: 'Main kaise karoon' },
  { t: 63.1, text: 'Karoon yeh bayaan' },
  { t: 68.0, text: 'Shuru se likhi dard ki is dastaan ki' },
  { t: 88.8, text: 'Dooriyan' },
  { t: 102.8, text: 'Khud se pareshan' },
  { t: 104.5, text: 'Lage mujhe zaalim yeh jahan' },
  { t: 106.8, text: 'Kaisi khala kaisi hai yeh bechainiyan' },
  { t: 111.5, text: 'Par yeh toh dil ne aah bhari hai' },
  { t: 116.8, text: 'Poora hoon main bas teri hi kami hai' },
  { t: 121.0, text: 'Toh phir main khud se karoon waade' },
  { t: 124.5, text: 'Sab kuch hi yun bhula de na' },
  { t: 127.5, text: 'Sataye teri yaadein mujhe' },
  { t: 131.0, text: 'Phir meri aankhon mein kaisi nami hai' },
  { t: 135.5, text: 'Poora hoon main bas teri hi kami hai' },
  { t: 140.0, text: 'Aur ek dariya' },
  { t: 144.5, text: 'Aansuon ka beh gaya' },
  { t: 150.0, text: 'Armaan toh dil mein mere reh gaya' },
  { t: 159.5, text: 'Main kaise karoon' },
  { t: 165.0, text: 'Karoon yeh bayaan' },
  { t: 169.0, text: 'Shuru se likhi dard ki is dastaan' },
  { t: 179.5, text: 'Saaya-e-fighan hai donon jahan' },
  { t: 187.5, text: 'Phir kyun tere aur mere' },
  { t: 196.6, text: 'Darmiyaan hai dooriyan' },
  { t: 204.5, text: 'Tu na jaane kabhi mujh mein kaise rehti hai' },
  { t: 211.5, text: 'Yeh mera jee tujhko bata ke' },
  { t: 218.0, text: 'Main kaise karoon' },
  { t: 221.5, text: 'Karoon yeh bayaan' },
  { t: 226.5, text: 'Shuru se likhi dard ki is dastaan' },
  { t: 236.5, text: 'Saaya-e-fighan hai donon jahan' },
  { t: 245.0, text: 'Phir kyun tere aur mere' },
  { t: 254.2, text: 'Darmiyaan hai dooriyan' },
  { t: 261.0, text: 'Yeh faasle hain kyun' },
  { t: 267.0, text: 'Tere aur mere dil mein yeh' },
  { t: 282.5, text: 'Dooriyan' },
];
