module.exports = [
  { t: 21.8, text: 'Kaise' },
  { t: 24.5, text: 'Saawan ki kaali ghataayein' },
  { t: 29.8, text: 'Jaane lagi' },
  { t: 32.6, text: 'Kaise' },
  { t: 35.3, text: 'Jeevan ki mujh pe sazaayein' },
  { t: 40.6, text: 'Aane lagi' },
  { t: 43.5, text: 'Jab hua main tera' },
  { t: 47.7, text: 'Bezubaan ho gaya' },
  { t: 52.6, text: 'Kaisi hai ye manzilein' },
  { t: 58.4, text: 'Benawa main hoon' },
  { t: 63.8, text: 'Phir na jaane' },
  { t: 67.3, text: 'Kyun wahi hai sila' },
  { t: 71.4, text: 'Jo dete sabhi hain mere' },
  { t: 76.7, text: 'Dil tu koi faisla' },
  { t: 82.2, text: 'To le le abhi' },
  { t: 99.7, text: 'Chaand taare par ganwaaya' },
  { t: 105.2, text: 'Maine kya kya paaya' },
  { t: 110.5, text: 'Aakhir kya tune mitaaya' },
  { t: 115.9, text: 'Jo dil mera socha na khud ka tha' },
  { t: 122.0, text: 'Jazbaati chunta tujhko' },
  { t: 125.8, text: 'Le gaya main talab' },
  { t: 129.7, text: 'Mera waqt tha tera' },
  { t: 133.0, text: 'Har khwaab tera' },
  { t: 136.2, text: 'Maanta gaya' },
  { t: 140.0, text: 'Phir na jaane' },
  { t: 142.5, text: 'Kyun wahi hai sila' },
  { t: 146.5, text: 'Jo dete sabhi hain mere' },
  { t: 152.0, text: 'Dil tu koi faisla' },
  { t: 157.4, text: 'To le le abhi' },
  { t: 182.6, text: 'Na jaane' },
  { t: 185.5, text: 'Kyun wahi hai sila' },
  { t: 189.6, text: 'Jo dete sabhi mere' },
  { t: 195.0, text: 'Dil tu koi faisla' },
  { t: 200.4, text: 'To le le abhi' },
  { t: 203.5, text: 'Phir na jaane' },
  { t: 207.0, text: 'Kyun wahi hai sila' },
  { t: 211.1, text: 'Jo dete sabhi mere' },
  { t: 216.5, text: 'Dil tu koi faisla' },
  { t: 221.8, text: 'To le le abhi' },
];
