module.exports = [
  { t: 36.6, text: 'Betaabiyan' },
  { t: 41.2, text: 'Bechainiyan' },
  { t: 43.6, text: 'Laayi yahan' },
  { t: 46.5, text: 'Jaaun kahan tumhare siva' },
  { t: 54.6, text: 'Yeh ranjishein' },
  { t: 59.3, text: 'Dukhon bhari yeh bandishein' },
  { t: 63.9, text: 'Sunaun kahan tumhare siva' },
  { t: 69.8, text: 'Hum beintehaa' },
  { t: 73.0, text: 'Pyaar tumhein karte hain' },
  { t: 76.5, text: 'Tum na samajh paoge' },
  { t: 79.8, text: 'Toh aise munh ko na modo' },
  { t: 82.5, text: 'Is dil ko na todo' },
  { t: 85.5, text: 'Ke hum hain sataaye hue' },
  { t: 89.0, text: 'Kaisa fasana hai' },
  { t: 93.0, text: 'Mera jahan tum ho' },
  { t: 96.5, text: 'Tum hi toh ho aarzoo' },
  { t: 100.5, text: 'Tum hi ho mera saara sukoon' },
  { t: 105.8, text: 'Tum guzra zamaana' },
  { t: 110.2, text: 'Meri subah tum ho' },
  { t: 114.5, text: 'Toota sitara hoon main' },
  { t: 119.5, text: 'Jab se haara hoon tumse main' },
  { t: 127.0, text: 'Nadaan hai veeraan hai' },
  { t: 130.3, text: 'Man yeh mera khud se anjaan hai' },
  { t: 134.8, text: 'Tum bekhabar' },
  { t: 138.3, text: 'Main besabar' },
  { t: 140.4, text: 'Tumhare liye kya yeh aasaan hai' },
  { t: 144.0, text: 'Dil mera gaaye kabhi' },
  { t: 146.5, text: 'Man ghabraaye hai kabhi' },
  { t: 149.5, text: 'Pyaar mujhe hai hua tumse' },
  { t: 153.0, text: 'Haan dum dum aankhon mein hi basti hai' },
  { t: 156.5, text: 'Yaadein sabhi' },
  { t: 158.5, text: 'Ishq mujhe hai hua tumse' },
  { t: 161.5, text: 'Toh aao na le jaao na' },
  { t: 165.0, text: 'Uljha hua hoon main dekho zara' },
  { t: 169.8, text: 'Ke meri aankhon mein gham hai' },
  { t: 172.5, text: 'Aur laakhon sitam' },
  { t: 174.7, text: 'Maine khud pe uthaaye hue' },
  { t: 178.5, text: 'Kaisa fasana hai' },
  { t: 183.5, text: 'Mera jahan tum ho' },
  { t: 187.0, text: 'Tum hi toh ho aarzoo' },
  { t: 190.5, text: 'Tum hi ho mera saara sukoon' },
  { t: 195.8, text: 'Tum guzra zamaana' },
  { t: 200.5, text: 'Meri subah tum ho' },
  { t: 205.0, text: 'Toota sitara hoon main' },
  { t: 210.0, text: 'Jab se haara hoon tumse main' },
];
