module.exports = [
  { t: 13.2, text: 'Panaahon mein' },
  { t: 15.7, text: 'Raat ki khamoshiyon mein' },
  { t: 19.5, text: 'Hawa chalne lage' },
  { t: 22.3, text: 'Aur zulf lehraaye' },
  { t: 26.0, text: 'Uski ada mein' },
  { t: 28.9, text: 'Na jaane hai kaisa nasha' },
  { t: 33.0, text: 'Woh aaye saamne' },
  { t: 34.8, text: 'Aur jaan le jaaye' },
  { t: 37.5, text: 'Uske kaanon mein jhumke gehne' },
  { t: 40.8, text: 'In aankhon ke kya kehne' },
  { t: 44.5, text: 'Shaida inka main ho gaya' },
  { t: 50.1, text: 'Aur uski paayal ki chhan chhan' },
  { t: 54.7, text: 'Rijhaaye dil ki dhadkan' },
  { t: 57.8, text: 'Woh mere jeene ki wajah' },
  { t: 64.0, text: 'Kya hai yeh mera marz' },
  { t: 70.1, text: 'Ya uski nazron ka asar' },
  { t: 75.6, text: 'Na jaane kyun' },
  { t: 80.0, text: 'Saansein meri na chale jaane kyun' },
  { t: 86.4, text: 'Shaamein kabhi na dhalein' },
  { t: 88.7, text: 'Khud se ho jaayein bekhabar' },
  { t: 92.1, text: 'Kar de jo hum pe woh nazar' },
  { t: 95.0, text: 'Na jaane kyun' },
  { t: 97.6, text: 'Woh humse chura le humein' },
  { t: 114.3, text: 'Pal do pal ki saanson mein reh jaaun' },
  { t: 118.5, text: 'Sochta hoon par keh na kabhi paaun' },
  { t: 122.0, text: 'Dil ki woh batiyan' },
  { t: 123.8, text: 'Yeh guzri ratiyan' },
  { t: 125.2, text: 'Main seh jaaun' },
  { t: 126.4, text: 'Do pal do pal ka aashiq toh main thehra' },
  { t: 131.8, text: 'Main bhool gaya woh haseen chehra' },
  { t: 134.8, text: 'Woh beeti hui sadiyon ki' },
  { t: 136.8, text: 'Behti hui nadiyon mein beh jaaun' },
  { t: 139.8, text: 'Jab uski aankhon se behta kaajal' },
  { t: 144.5, text: 'Kare is dil ko paagal' },
  { t: 147.0, text: 'Kaisi mujh pe hai yeh saza' },
  { t: 152.5, text: 'Aur uski kaali zulfon ke' },
  { t: 155.5, text: 'Saaye se mera dil sharmaaye' },
  { t: 159.5, text: 'Main toh ho jaaun fanaa' },
  { t: 166.5, text: 'Ashkon ki dhaaron mein' },
  { t: 172.9, text: 'Kaise samete yeh' },
  { t: 178.0, text: 'Na jaane kyun' },
  { t: 182.4, text: 'Saansein meri na chale jaane kyun' },
  { t: 188.8, text: 'Shaamein kabhi na dhalein' },
  { t: 191.6, text: 'Pal mein hi jaayenge bikhar' },
  { t: 194.5, text: 'Kar de woh hum pe jo nazar' },
  { t: 197.2, text: 'Na jaane kyun' },
  { t: 199.9, text: 'Woh humse chura le humein' },
];
